# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
np_1d = np.array([1,2,3,4,5,6])

# Create a 2-dimensional NumPy array using np.array()
np_2d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

# Create a 3-dimensional Numpy array using np.array()
np_3d = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# print("Shape      : ")
# print("Dimensions : ")
# print("Data Type  : ")
# print("Size       : ")
# print("Type       : ")

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape      : ",np_1d.shape)
print("Dimensions : ",np_1d.ndim)
print("Data Type  : ",np_1d.dtype)
print("Size       : ",np_1d.size)
print("Type       : ",type(np_1d))

Shape      :  (6,)
Dimensions :  1
Data Type  :  int64
Size       :  6
Type       :  <class 'numpy.ndarray'>


In [7]:
# Attributes of 2-dimensional array
print("Shape      : ",np_2d.shape)
print("Dimensions : ",np_2d.ndim)
print("Data Type  : ",np_2d.dtype)
print("Size       : ",np_2d.size)
print("Type       : ",type(np_2d))

Shape      :  (2, 6)
Dimensions :  2
Data Type  :  int64
Size       :  12
Type       :  <class 'numpy.ndarray'>


In [8]:
# Attributes of 3-dimensional array
print("Shape      : ",np_3d.shape)
print("Dimensions : ",np_3d.ndim)
print("Data Type  : ",np_3d.dtype)
print("Size       : ",np_3d.size)
print("Type       : ",type(np_3d))

Shape      :  (2, 2, 6)
Dimensions :  3
Data Type  :  int64
Size       :  24
Type       :  <class 'numpy.ndarray'>


In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 

df = pd.DataFrame(np_2d)
df

0  1  2   3   4   5
0  1  2  3   4   5   6
1  7  8  9  10  11  12

In [12]:
# Create an array of shape (10, 2) with only ones
arr_1 = np.ones((10,2))
arr_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
arr_2 = np.zeros((7,2,3))
arr_2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
arr_3 = np.arange(0,100,3)
arr_3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_4 = np.random.randint(0,10,(7,2))
arr_4

array([[0, 8],
       [8, 2],
       [7, 3],
       [5, 4],
       [6, 1],
       [7, 1],
       [4, 7]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_5 = np.random.rand(3,5)
arr_5

array([[0.0066004 , 0.95943444, 0.21904653, 0.02666776, 0.87944417],
       [0.48466961, 0.18019035, 0.53102629, 0.11505427, 0.59422614],
       [0.36869873, 0.10773919, 0.1117433 , 0.72142445, 0.40573036]])

In [19]:
# Set the random seed to 42
see = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_6 = np.random.randint(0,10,(4,6))
arr_6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_6 = np.random.randint(1,10,(4,6))
print("random numbers between 1 & 10 of size (3, 7) : ",arr_6)

# Find the unique numbers in the array you just created
arr_7 = np.unique(arr_6)
print("Unique Numbers : ",arr_7)

random numbers between 1 & 10 of size (3, 7) :  [[7 4 7 3 6 2]
 [9 5 6 4 7 9]
 [7 1 1 9 9 4]
 [9 3 7 6 8 9]]
Unique Numbers :  [1 2 3 4 5 6 7 8 9]


In [26]:
# Find the 0'th index of the latest array you created
print(arr_6[0])

[7 4 7 3 6 2]


In [27]:
# Get the first 2 rows of latest array you created
print(arr_6[0:2])

[[7 4 7 3 6 2]
 [9 5 6 4 7 9]]


In [28]:
# Get the first 2 values of the first 2 rows of the latest array
print(arr_6[0:2,0:2])

[[7 4]
 [9 5]]


In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a = np.random.randint(0,10,(3,5))
b = np.ones((3,5))

In [31]:
# Add the two arrays together
c = a + b

In [33]:
# Create another array of ones of shape (5, 3)
d = np.ones((5,3))

In [34]:
# Try add the array of ones and the other most recent array together
f = b + d

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [35]:
# Create another array of ones of shape (3, 5)
g = np.ones((3,5))

In [37]:
# Subtract the new array of ones from the other most recent array
h = g - c

In [51]:
i = np.dot(h,d)
i

array([[-22., -22., -22.],
       [-23., -23., -23.],
       [-19., -19., -19.]])

In [52]:
# Take the latest array to the power of 2 using '**'
i ** 2

array([[484., 484., 484.],
       [529., 529., 529.],
       [361., 361., 361.]])

In [53]:
# Do the same thing with np.square()
np.square(i)

array([[484., 484., 484.],
       [529., 529., 529.],
       [361., 361., 361.]])

In [54]:
# Find the mean of the latest array using np.mean()
np.mean(i)

-21.333333333333332

In [55]:
# Find the maximum of the latest array using np.max()
np.max(i)

-19.0

In [56]:
# Find the minimum of the latest array using np.min()
np.min(i)

-23.0

In [58]:
# Find the standard deviation of the latest array
np.std(i)

1.699673171197595

In [62]:
# Find the variance of the latest array
np.var(i)

2.8888888888888893

In [65]:
# Reshape the latest array to (3, 5, 1)
j = h.reshape(3,5,1)

In [66]:
# Transpose the latest array
j.T

array([[[-4., -5.,  0.],
        [ 0., -7., -9.],
        [-2., -8., -3.],
        [-9., -3., -6.],
        [-7.,  0., -1.]]])

In [80]:
k=np.array([1,2,3,4,5])
np.where(4)

(array([0]),)

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.